version: '3'
services:
  ytb:
    container_name: ytb
    build:
      context: ./api
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db

  db:
    image: postgres:$VERSION
    container_name: postgres
    command: -c "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - 5432:5432
    volumes:
      - db_master:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf 
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  db_master: