version: '3'
services:
  ytb:
    container_name: ytb
    image: ytb:1.2
    build:
      context: ./api
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    depends_on:
      - db

  frontend:
    container_name: frontend
    image: frontend:1.0
    build: 
      context: ./frontend
    command: streamlit run main.py --server.port=8503 
    ports:
      - 8503:8503
    volumes:
      - ./frontend/streamlit:/usr/share/nginx/html/streamlit/
    environment:
      TZ: 'Asia/Tokyo'
    depends_on:
      - db
      - ytb

  db:
    image: postgres:$VERSION
    container_name: postgres
    command: -c "config_file=/etc/postgresql/postgresql.conf"
    ports:
      - 5432:5432
    volumes:
      - db_master:/var/lib/postgresql/data
      - ./script:/docker-entrypoint-initdb.d
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      TZ: "Asia/Tokyo"
    environment:
      - POSTGRES_USER=$POSTGRES_USER
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD

volumes:
  db_master:


# end of docker-compose