version: '3'

services:
  main:
    build:
      context: ./api
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - 8000:8000
    environment:
      TZ: 'Asia/Tokyo'

  db:
    image: mysql:8.0
    platform: linux/x86_64  
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: 'demo'
      TZ: 'Asia/Tokyo'
    volumes:
      - mysql_data:/var/lib/mysql
      # confファイルにマウントしてエンコードを変更
      - ./api/mysql.conf:/etc/mysql/conf.d/my.cnf
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 33306:3306

  cron:
    build:
      context: ./cron
    environment:
      TZ: 'Asia/Tokyo'
    volumes:
      - ./:/workspace
    stdin_open: true
    tty: true

  st_server:
    build: 
      context: ./st_server
    command: streamlit run streamlit1/sample_1.py --server.port=8503 
    ports:
      - 8503:8503
    volumes:
      - ./st_server/public/streamlit1:/usr/share/nginx/html/streamlit1
    environment:
      TZ: 'Asia/Tokyo'

  nginx:
    build: 
      context: ./Nginx
    ports:
      - 80:80
    links:
      - st_server
    volumes:
      - ./Nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./Nginx/public/index.html:/usr/share/nginx/html/index.html
    environment:
      TZ: 'Asia/Tokyo'

volumes:
  mysql_data: